(PIE-423) Support multiple events in a single post
puppetlabs/puppetlabs-splunk_hec pull request #66
Opened 2020-11-30 11:19 UTC by gregohardy

2020-11-30 16:52 UTC, gregohardy commented
Requires PIE-421 and and rebase

2020-11-30 19:46 UTC, gsparks requested changes
Would you mind adding a note to the commit about adding commits as well as events?

2020-12-01 16:20 UTC, gsparks approved these changes

2020-12-01 16:30 UTC, gsparks approved these changes

2020-12-01 16:30 UTC, merged